apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logger-pingpong-claim
spec:
  storageClassName: logger-pingpong-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
