apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-data
          persistentVolumeClaim:
            claimName: todo-app-claim

      containers:
        - name: todo-app
          image: asfalfa/todo-app:v7
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: IMAGE_FILE
              value: "/data/image.jpg"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: image-data
              mountPath: /data
