apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: logger-pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-pingpong
  template:
    metadata:
      labels:
        app: logger-pingpong
    spec:
      containers:
        - name: random-logger
          image: asfalfa/random-logger:v7
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: PINGS_URL
              value: "http://localhost:8081/pings"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logger-config
                  key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          ports:
            - containerPort: 8080

        - name: ping-pong
          image: asfalfa/ping-pong:v6
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8081"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres.exercises.svc.cluster.local:5432/pingpong"
          ports:
            - containerPort: 8081

      volumes:
        - name: config-volume
          configMap:
            name: logger-config
            items:
              - key: information.txt
                path: information.txt
