apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: MODE
              value: "log-only"
            - name: ENDPOINT_URL
              value: ""
