apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: MODE
              value: "forward"
            - name: ENDPOINT_URL
              value: "http://generic-receiver.default.svc.cluster.local/webhook"
